### ISSUE TITLE
Error when trying to save playlist  Error: Cannot call invokeAndWait

### ISSUE THREAD

**Issue by Bensonmaam** [jajuk-team/jajuk#1986]
version 1.10.7 gute Laune
OS Win 7/64
Java 1.7 /64 but problem occurs unter /32, too

In normal mode nothing seems to happen when pressing save playlist.
So I started jakuk from the command line. So I got this error message.

E:\PROGRAMMEx86\Jajuk\bin>c:\windows\System32\java.exe -jar jajuk.jar
2015/04/03 12:35:57 [INFO] ******************JAJUK******************  [main] (Ma
in.java:106)
2015/04/03 12:35:57 [INFO] Version: 1.10.7  [main] (Main.java:106)
2015/04/03 12:35:57 [DEBUG] ----------------------------------------------------
------------------------  [main] (Main.java:110)
2015/04/03 12:35:57 [DEBUG] Starting Jajuk 1.10.7 <Gute Laune> Build: 2014/08/25
 23:50  [main] (Main.java:111)
2015/04/03 12:35:57 [DEBUG] Register: "PARAMETERS_CHANGE" by: org.jajuk.ui.helpe
rs.FontManager@1eed723b  [main] (ObservationManager.java:65)
Exception in thread "AWT-EventQueue-0" java.lang.Error: Cannot call invokeAndWai
t from the event dispatcher thread
        at java.awt.EventQueue.invokeAndWait(Unknown Source)
        at java.awt.EventQueue.invokeAndWait(Unknown Source)
        at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
        at org.jajuk.base.Playlist.saveAs(Playlist.java:709)
        at org.jajuk.ui.views.QueueView.actionPerformed(QueueView.java:487)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at org.jvnet.substance.utils.RolloverButtonListener.mouseReleased(Rollov
erButtonListener.java:111)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Bensonmaam** [comment]
Toll - funktioniert wieder. Vielen Dank für die schnelle Reaktion,
