### ISSUE TITLE
java exception at start up jajuk 1.10.9 on Linux Fedora 23 

### ISSUE THREAD

**Issue by albertomp** [jajuk-team/jajuk#2005]
Hi, I have installed jajuk 1.10.9 on a Linux Fedora 23 system with the rpm package. The software doesnt start, when I run Jajuk on a terminal I get the next message:

Detected a 64-bit operating system, using the lib64 native library directory.
Java version in the default path is: 1.8
java -client -Xms20M -Xmx2G -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -Xverify:none -Djava.library.path=/usr/lib/jni:/usr/lib:/usr/share/jajuk/lib64:/usr/share/jajuk/bin/../lib/lib64 -jar jajuk.jar -notest
2016/03/17 21:06:05 [INFO] *****************_JAJUK**_**************\*  [main](Main.java:106) 
2016/03/17 21:06:05 [INFO] Version: 1.10.9  [main](Main.java:106) 
2016/03/17 21:06:05 [DEBUG] ----------------------------------------------------------------------------  [main](Main.java:110) 
2016/03/17 21:06:05 [DEBUG] Starting Jajuk 1.10.9 <Gute Laune> Build: 2016/02/22 22:41  [main](Main.java:111) 
2016/03/17 21:06:05 [DEBUG] Register: "PARAMETERS_CHANGE" by: org.jajuk.ui.helpers.FontManager@7b1d7fff  [main](ObservationManager.java:65) 
2016/03/17 21:06:05 [ERROR] null / null  [AWT-EventQueue-0](FontManager.java:149) 
java.awt.HeadlessException
    at sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:226)
    at org.pushingpixels.substance.internal.utils.SubstanceSizeUtils.resetPointsToPixelsRatio(SubstanceSizeUtils.java:980)
    at org.pushingpixels.substance.api.SubstanceLookAndFeel.setFontPolicy(SubstanceLookAndFeel.java:1564)
    at org.jajuk.ui.helpers.FontManager$1.run(FontManager.java:147)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2016/03/17 21:06:05 [ERROR](106) Excepción no capturada  [main](Main.java:193) 
java.lang.reflect.InvocationTargetException
    at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
    at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
    at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
    at org.jajuk.services.startup.StartupGUIService.launchSplashScreen(StartupGUIService.java:89)
    at org.jajuk.Main.main(Main.java:135)
Caused by: java.awt.HeadlessException
    at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
    at java.awt.Window.<init>(Window.java:536)
    at java.awt.Frame.<init>(Frame.java:420)
    at java.awt.Frame.<init>(Frame.java:385)
    at javax.swing.JFrame.<init>(JFrame.java:189)
    at ext.JSplash.<init>(JSplash.java:100)
    at org.jajuk.services.startup.StartupGUIService$1.run(StartupGUIService.java:92)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Thanks a lot for your help. I have been a happy jajuk user longtime.

**Comment by bflorat** [comment]
Guess you have an headless JRE installed (for servers only).
Can you perform a rpm -qa | grep java ?
I have no problem under centos with package
java-1.7.0-openjdk-1.7.0.45-2.4.3.3.el6.i686

**Comment by centic9** [comment]
I think we can close this for now as there was no reply at all and it is likely an installation issue.
